"""animal table

Revision ID: f18643aea10e
Revises: 
Create Date: 2024-02-15 15:44:08.916024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18643aea10e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('binomial_name', sa.String(length=100), nullable=False),
    sa.Column('genus', sa.String(length=100), nullable=False),
    sa.Column('family', sa.String(length=100), nullable=False),
    sa.Column('order', sa.String(length=100), nullable=False),
    sa.Column('class', sa.String(length=100), nullable=False),
    sa.Column('phylum', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal')
    # ### end Alembic commands ###
